-- DROP USER ANONYMOUS;

CREATE USER ANONYMOUS
-- IDENTIFIED BY <password>
;

CREATE TABLE "ANONYMOUS"."PRODUCT" 
   (	"PRODUCT_ID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PRODUCT_TYPE" NUMBER NOT NULL ENABLE, 
	"BOOK" NVARCHAR2(255) NOT NULL ENABLE, 
	"PRODUCT_NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"REF_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"GL" NVARCHAR2(255) NOT NULL ENABLE, 
	"SPOT" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"CALYPSO_LE" NVARCHAR2(255) NOT NULL ENABLE, 
	"SHOW_FORMA" NUMBER, 
	"SHOW_DORM" NUMBER, 
	"SHOW_ALLOCATION" NUMBER, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	 CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "ANONYMOUS"."PRODUCT" ADD CONSTRAINT "FK_PRODUCT_PRODUCTCATEGORY" FOREIGN KEY ("PRODUCT_TYPE")
	  REFERENCES "ANONYMOUS"."PRODUCT_CATEGORY" ("ID") ENABLE;

CREATE UNIQUE INDEX "ANONYMOUS"."PRODUCT_PK" ON "ANONYMOUS"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."PRODUCT_CATEGORY" 
   (	"ID" NUMBER(38,0), 
	"CATEGORY" NVARCHAR2(255), 
	"SHOW_DORM" NUMBER, 
	"SHOW_ALLOCATION" NUMBER, 
	"SHOW_FORMA" NUMBER, 
	 CONSTRAINT "PRODUCT_CATEGORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

CREATE UNIQUE INDEX "ANONYMOUS"."PRODUCT_CATEGORY_PK" ON "ANONYMOUS"."PRODUCT_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."RATE" 
   (	"ID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PRIMARY_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"SECONDARY_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"RATE" BINARY_FLOAT NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.865 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM') NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.865 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM'), 
	 CONSTRAINT "RATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

CREATE UNIQUE INDEX "ANONYMOUS"."RATE_PK" ON "ANONYMOUS"."RATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."ROLES" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLES" NVARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

CREATE UNIQUE INDEX "ANONYMOUS"."ROLES_PK" ON "ANONYMOUS"."ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."SMTP" 
   (	"ID" VARCHAR2(100), 
	"SERVICE" NVARCHAR2(255) NOT NULL ENABLE, 
	"USER" NVARCHAR2(255) NOT NULL ENABLE, 
	"PASSWORD" NVARCHAR2(255) NOT NULL ENABLE, 
	"FROM" NVARCHAR2(255) NOT NULL ENABLE, 
	"SUBJECT" NVARCHAR2(255) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.925 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM') NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.925 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM'), 
	 CONSTRAINT "SMTP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

CREATE UNIQUE INDEX "ANONYMOUS"."SMTP_PK" ON "ANONYMOUS"."SMTP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."TRADE" 
   (	"ID" VARCHAR2(100), 
	"CUSTOMER_REF" NVARCHAR2(100), 
	"ACC_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"ACC_NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"ACC_BALANCE" NUMBER(22,2) NOT NULL ENABLE, 
	"ACC_CURRENCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"BRANCH" NVARCHAR2(255) NOT NULL ENABLE, 
	"DIRECTION" NVARCHAR2(255) NOT NULL ENABLE, 
	"DIRECTION_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"WE_SELL" NUMBER(22,2) NOT NULL ENABLE, 
	"WE_SELL_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"DEBIT_AMOUNT" NUMBER(22,2), 
	"DEBIT_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"REF_AMOUNT" NUMBER(22,2), 
	"REF_CCY" NVARCHAR2(255) NOT NULL ENABLE, 
	"COMMENT" NVARCHAR2(255), 
	"AUTHORIZER_COMMENT" NVARCHAR2(255), 
	"STATUS" NUMBER, 
	"DORM_ACCNO" NUMBER, 
	"DORM_ACCNAME" NVARCHAR2(255), 
	"TRANSFER_PURPOSE" NVARCHAR2(255), 
	"FORM_A_NO" NVARCHAR2(255), 
	"PASSPORT_NO" NVARCHAR2(255), 
	"TRAVEL_COUNTRY" NVARCHAR2(255), 
	"E_TICKET_NO" NVARCHAR2(255), 
	"APPLICATION_NO" NVARCHAR2(255), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"PRODUCT_ID" NVARCHAR2(255) NOT NULL ENABLE, 
	"EXCHANGE_RATE2" NUMBER(22,4) NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"TRADE_DATE" DATE NOT NULL ENABLE, 
	"TRAVEL_DATE" DATE NOT NULL ENABLE, 
	"SELL_SETTLE_DATE" DATE NOT NULL ENABLE, 
	"CUSTOMER_DEBIT_SETTLE_DATE" DATE NOT NULL ENABLE, 
	"REFERENCE_CCY_SETTLE_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(100), 
	"EXCHANGE_RATE1" NUMBER(22,4) NOT NULL ENABLE, 
	 CONSTRAINT "TRADE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

ALTER TABLE "ANONYMOUS"."TRADE" ADD CONSTRAINT "FK_TRADE_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ANONYMOUS"."PRODUCT" ("PRODUCT_ID") ENABLE;

CREATE SEQUENCE ANONYMOUS.TRADE_ID_SEQ INCREMENT BY 1 MINVALUE 2 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "ANONYMOUS"."TRADE_ID" BEFORE  INSERT ON TRADE 
FOR EACH ROW
DECLARE 
	PREFIX NUMBER ; 
BEGIN
	SELECT PRODUCT.PRODUCT_TYPE  INTO PREFIX
	FROM PRODUCT WHERE PRODUCT_ID  = :NEW.PRODUCT_ID;
	SELECT CONCAT(LPAD( PREFIX,3,'0'),LPAD( TRADE_ID_SEQ.NEXTVAL,3,'0')) INTO :NEW.CUSTOMER_REF FROM DUAL;
END;

ALTER TRIGGER "ANONYMOUS"."TRADE_ID" ENABLE;

CREATE UNIQUE INDEX "ANONYMOUS"."TRADE_PK" ON "ANONYMOUS"."TRADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;

CREATE TABLE "ANONYMOUS"."USER" 
   (	"USERNAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"FIRST_NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"LAST_NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"PASSWORD" NVARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL_ID" NVARCHAR2(255) NOT NULL ENABLE, 
	"PHONE_NO" NVARCHAR2(255), 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.783 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM') NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT TO_TIMESTAMP_TZ('2023-09-05 13:28:57.783 +00:00','YYYY-MM-DD HH24:MI:SS.FFTZH:TZM'), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER, 
	"IS_ACTIVE" NVARCHAR2(255) NOT NULL ENABLE, 
	"NOTIFICATION" NUMBER, 
	"ENVIRONMENT" NVARCHAR2(255), 
	 CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;

ALTER TABLE "ANONYMOUS"."USER" ADD CONSTRAINT "FK_USER_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ANONYMOUS"."ROLES" ("ID") ENABLE;

CREATE UNIQUE INDEX "ANONYMOUS"."USER_PK" ON "ANONYMOUS"."USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
;


CREATE TABLE ANONYMOUS.USER_PRODUCTS (
	USERID NVARCHAR2(255) NOT NULL,
	PRODUCTID NVARCHAR2(255) NOT NULL,
	CONSTRAINT SYS_C008432 PRIMARY KEY (USERID,PRODUCTID)
);
CREATE UNIQUE INDEX SYS_C008432 ON ANONYMOUS.USER_PRODUCTS (USERID,PRODUCTID);
-- ANONYMOUS.USER_PRODUCTS foreign keys

ALTER TABLE "ANONYMOUS"."USER_PRODUCTS" ADD FOREIGN KEY ("USERID")
	  REFERENCES "ANONYMOUS"."USER" ("ID") ENABLE;
  ALTER TABLE "ANONYMOUS"."USER_PRODUCTS" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "ANONYMOUS"."PRODUCT" ("PRODUCT_ID") ENABLE;
  
CREATE SEQUENCE  "ANONYMOUS".TRAN_ID_SEQ  MINVALUE 120 MAXVALUE 999999999999999999999999 INCREMENT BY 44 START WITH 2440 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE OR REPLACE TRIGGER "ANONYMOUS".TRAN_ID BEFORE INSERT ON "ANONYMOUS".TRANSACTION_LOG
FOR EACH ROW
BEGIN

    SELECT TRAN_ID_SEQ.NEXTVAL INTO :NEW.TRANSACTION_ID FROM DUAL;
END;